name: CI

on:
  push:
    branches:
    - tests

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: xcodebuild -project 'Busik/Busik.xcodeproj' -scheme 'Busik' -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=15.2' clean test
      - name: Build
        run: xcodebuild -project 'Busik/Busik.xcodeproj' -scheme 'Busik' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
